name: cross-talker-generalization
channels:
  - conda-forge
dependencies:
  - python=3.9.18
  - h5py=3.14.0
  - joblib=1.5.2
  - matplotlib=3.9.4
  - numba=0.60.0
  - numpy=1.26.4
  - pandas=2.3.3
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - threadpoolctl=3.6.0
  - pip

# Statistical models additionally require R 4.4.1 and lme4 1.1-35.5.
